spring:
  application:
    name: myApp
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        format: properties
        prefixes: config/myapp

  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

SECRET_KEY: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"